# Generated by Django 5.1.5 on 2025-01-26 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('comp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=3)),
                ('exchange_rate_to_usd', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('vouch_type_id', models.CharField(max_length=20)),
                ('vouch_id', models.CharField(max_length=50)),
                ('msicid', models.CharField(max_length=50)),
                ('docid', models.CharField(max_length=50)),
                ('reservation_no', models.CharField(max_length=50)),
                ('vouch_date', models.DateField()),
                ('selling_fare', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_invoice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('customer', models.CharField(max_length=255)),
                ('agent_name', models.CharField(max_length=255)),
                ('airline', models.CharField(blank=True, max_length=255)),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('hotel_name', models.CharField(blank=True, max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.currency')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.documenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'year'], name='dashboard_i_company_bb4064_idx'), models.Index(fields=['vouch_date'], name='dashboard_i_vouch_d_0375b8_idx'), models.Index(fields=['customer'], name='dashboard_i_custome_251485_idx'), models.Index(fields=['agent_name'], name='dashboard_i_agent_n_b1f13f_idx')],
            },
        ),
    ]
