# Generated by Django 5.1.5 on 2025-01-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_invoiceview'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoiceview',
            table='mv_IAMS_INVOICE_INFO',
        ),
    ]
