# Generated by Django 5.1.5 on 2025-01-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_invoiceview_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceview',
            options={'managed': False, 'ordering': ['-vouch_date']},
        ),
    ]
