# Generated by Django 5.1.5 on 2025-01-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_invoiceview_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoiceview',
            table='MV_IAMS_INVOICE_INFO',
        ),
    ]
