# Generated by Django 5.1.5 on 2025-01-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_provider_agent_activity_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sales_officer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
