# Generated by Django 5.1.5 on 2025-01-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_sale_sales_officer_sale_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sales_officer',
        ),
    ]
